// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/base.go

// Package mock_repository is a generated GoMock package.
package repository

import (
	reflect "reflect"
	model "test-stockbit/pkg/model"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// InsertLoggerRepository mocks base method.
func (m *MockRepository) InsertLoggerRepository(logger *model.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLoggerRepository", logger)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLoggerRepository indicates an expected call of InsertLoggerRepository.
func (mr *MockRepositoryMockRecorder) InsertLoggerRepository(logger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLoggerRepository", reflect.TypeOf((*MockRepository)(nil).InsertLoggerRepository), logger)
}
