// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: test-stockbit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Logger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Transport string `protobuf:"bytes,2,opt,name=Transport,proto3" json:"Transport,omitempty"`
	Logging   string `protobuf:"bytes,3,opt,name=Logging,proto3" json:"Logging,omitempty"`
	Level     string `protobuf:"bytes,4,opt,name=Level,proto3" json:"Level,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *Logger) Reset() {
	*x = Logger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_stockbit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger) ProtoMessage() {}

func (x *Logger) ProtoReflect() protoreflect.Message {
	mi := &file_test_stockbit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger.ProtoReflect.Descriptor instead.
func (*Logger) Descriptor() ([]byte, []int) {
	return file_test_stockbit_proto_rawDescGZIP(), []int{0}
}

func (x *Logger) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Logger) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *Logger) GetLogging() string {
	if x != nil {
		return x.Logging
	}
	return ""
}

func (x *Logger) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logger) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Logger) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListMovieRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey     string `protobuf:"bytes,1,opt,name=Apikey,proto3" json:"Apikey,omitempty"`
	SearchWord string `protobuf:"bytes,2,opt,name=SearchWord,proto3" json:"SearchWord,omitempty"`
	Pagination string `protobuf:"bytes,3,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
}

func (x *ListMovieRequest) Reset() {
	*x = ListMovieRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_stockbit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovieRequest) ProtoMessage() {}

func (x *ListMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_stockbit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovieRequest.ProtoReflect.Descriptor instead.
func (*ListMovieRequest) Descriptor() ([]byte, []int) {
	return file_test_stockbit_proto_rawDescGZIP(), []int{1}
}

func (x *ListMovieRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *ListMovieRequest) GetSearchWord() string {
	if x != nil {
		return x.SearchWord
	}
	return ""
}

func (x *ListMovieRequest) GetPagination() string {
	if x != nil {
		return x.Pagination
	}
	return ""
}

type DetailMovieByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apikey string `protobuf:"bytes,1,opt,name=Apikey,proto3" json:"Apikey,omitempty"`
	ID     string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Plot   string `protobuf:"bytes,3,opt,name=Plot,proto3" json:"Plot,omitempty"`
}

func (x *DetailMovieByIDRequest) Reset() {
	*x = DetailMovieByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_stockbit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailMovieByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailMovieByIDRequest) ProtoMessage() {}

func (x *DetailMovieByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_stockbit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailMovieByIDRequest.ProtoReflect.Descriptor instead.
func (*DetailMovieByIDRequest) Descriptor() ([]byte, []int) {
	return file_test_stockbit_proto_rawDescGZIP(), []int{2}
}

func (x *DetailMovieByIDRequest) GetApikey() string {
	if x != nil {
		return x.Apikey
	}
	return ""
}

func (x *DetailMovieByIDRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DetailMovieByIDRequest) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

type ListMovieResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search       []byte `protobuf:"bytes,1,opt,name=Search,proto3" json:"Search,omitempty"`
	TotalResults string `protobuf:"bytes,2,opt,name=TotalResults,proto3" json:"TotalResults,omitempty"`
	Response     string `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *ListMovieResponse) Reset() {
	*x = ListMovieResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_stockbit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovieResponse) ProtoMessage() {}

func (x *ListMovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_stockbit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovieResponse.ProtoReflect.Descriptor instead.
func (*ListMovieResponse) Descriptor() ([]byte, []int) {
	return file_test_stockbit_proto_rawDescGZIP(), []int{3}
}

func (x *ListMovieResponse) GetSearch() []byte {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ListMovieResponse) GetTotalResults() string {
	if x != nil {
		return x.TotalResults
	}
	return ""
}

func (x *ListMovieResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type DetailMoviesByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response []byte `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *DetailMoviesByIDResponse) Reset() {
	*x = DetailMoviesByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_stockbit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailMoviesByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailMoviesByIDResponse) ProtoMessage() {}

func (x *DetailMoviesByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_stockbit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailMoviesByIDResponse.ProtoReflect.Descriptor instead.
func (*DetailMoviesByIDResponse) Descriptor() ([]byte, []int) {
	return file_test_stockbit_proto_rawDescGZIP(), []int{4}
}

func (x *DetailMoviesByIDResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_test_stockbit_proto protoreflect.FileDescriptor

var file_test_stockbit_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x62, 0x69, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a,
	0x06, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x6a, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54, 0x0a,
	0x16, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x70, 0x69, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x70, 0x69, 0x6b, 0x65, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x6c, 0x6f, 0x74, 0x22, 0x6b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x36, 0x0a, 0x18, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa2, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x10, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a,
	0x0a, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_test_stockbit_proto_rawDescOnce sync.Once
	file_test_stockbit_proto_rawDescData = file_test_stockbit_proto_rawDesc
)

func file_test_stockbit_proto_rawDescGZIP() []byte {
	file_test_stockbit_proto_rawDescOnce.Do(func() {
		file_test_stockbit_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_stockbit_proto_rawDescData)
	})
	return file_test_stockbit_proto_rawDescData
}

var file_test_stockbit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_stockbit_proto_goTypes = []interface{}{
	(*Logger)(nil),                   // 0: proto.Logger
	(*ListMovieRequest)(nil),         // 1: proto.ListMovieRequest
	(*DetailMovieByIDRequest)(nil),   // 2: proto.DetailMovieByIDRequest
	(*ListMovieResponse)(nil),        // 3: proto.ListMovieResponse
	(*DetailMoviesByIDResponse)(nil), // 4: proto.DetailMoviesByIDResponse
}
var file_test_stockbit_proto_depIdxs = []int32{
	1, // 0: proto.Service.ListMovies:input_type -> proto.ListMovieRequest
	2, // 1: proto.Service.DetailMoviesByID:input_type -> proto.DetailMovieByIDRequest
	3, // 2: proto.Service.ListMovies:output_type -> proto.ListMovieResponse
	4, // 3: proto.Service.DetailMoviesByID:output_type -> proto.DetailMoviesByIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_stockbit_proto_init() }
func file_test_stockbit_proto_init() {
	if File_test_stockbit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_stockbit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Logger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_stockbit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMovieRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_stockbit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailMovieByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_stockbit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMovieResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_stockbit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailMoviesByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_stockbit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_stockbit_proto_goTypes,
		DependencyIndexes: file_test_stockbit_proto_depIdxs,
		MessageInfos:      file_test_stockbit_proto_msgTypes,
	}.Build()
	File_test_stockbit_proto = out.File
	file_test_stockbit_proto_rawDesc = nil
	file_test_stockbit_proto_goTypes = nil
	file_test_stockbit_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	ListMovies(ctx context.Context, in *ListMovieRequest, opts ...grpc.CallOption) (*ListMovieResponse, error)
	DetailMoviesByID(ctx context.Context, in *DetailMovieByIDRequest, opts ...grpc.CallOption) (*DetailMoviesByIDResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) ListMovies(ctx context.Context, in *ListMovieRequest, opts ...grpc.CallOption) (*ListMovieResponse, error) {
	out := new(ListMovieResponse)
	err := c.cc.Invoke(ctx, "/proto.Service/ListMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DetailMoviesByID(ctx context.Context, in *DetailMovieByIDRequest, opts ...grpc.CallOption) (*DetailMoviesByIDResponse, error) {
	out := new(DetailMoviesByIDResponse)
	err := c.cc.Invoke(ctx, "/proto.Service/DetailMoviesByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	ListMovies(context.Context, *ListMovieRequest) (*ListMovieResponse, error)
	DetailMoviesByID(context.Context, *DetailMovieByIDRequest) (*DetailMoviesByIDResponse, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) ListMovies(context.Context, *ListMovieRequest) (*ListMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMovies not implemented")
}
func (*UnimplementedServiceServer) DetailMoviesByID(context.Context, *DetailMovieByIDRequest) (*DetailMoviesByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetailMoviesByID not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_ListMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ListMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/ListMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ListMovies(ctx, req.(*ListMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DetailMoviesByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetailMovieByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DetailMoviesByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/DetailMoviesByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DetailMoviesByID(ctx, req.(*DetailMovieByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMovies",
			Handler:    _Service_ListMovies_Handler,
		},
		{
			MethodName: "DetailMoviesByID",
			Handler:    _Service_DetailMoviesByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test-stockbit.proto",
}
